'use client';

import { useState, useEffect } from 'react';
import { 
  Dialog, 
  DialogContent, 
  DialogDescription, 
  DialogFooter, 
  DialogHeader, 
  DialogTitle 
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { 
  User, 
  GraduationCap, 
  Calendar,
  DollarSign,
  CheckCircle,
  AlertCircle
} from 'lucide-react';
import { 
  AdmissionApplication, 
  Intake, 
  Program, 
  StudentProfile,
  generateStudentNumber 
} from '@/lib/database';
import { useLiveQuery } from 'dexie-react-hooks';
import { db } from '@/lib/database';

interface StudentConversionDialogProps {
  application: AdmissionApplication | null;
  isOpen: boolean;
  onClose: () => void;
  onConvert: (studentProfile: StudentProfile) => void;
}

export const StudentConversionDialog = ({ 
  application, 
  isOpen, 
  onClose, 
  onConvert 
}: StudentConversionDialogProps) => {
  const [enrollmentDate, setEnrollmentDate] = useState('');
  const [currentYear, setCurrentYear] = useState('1');
  const [currentSemester, setCurrentSemester] = useState('1');
  const [isSubmitting, setIsSubmitting] = useState(false);

  // Fetch intake and program details
  const intake = useLiveQuery(() => 
    application?.intakeId ? db.intakes.get(application.intakeId) : null
  );
  const program = useLiveQuery(() => 
    application?.programId ? db.programs.get(application.programId) : null
  );

  useEffect(() => {
    if (isOpen && application) {
      // Set default enrollment date to today
      setEnrollmentDate(new Date().toISOString().split('T')[0]);
    }
  }, [isOpen, application]);

  const handleConvert = async () => {
    if (!application || !intake || !program) return;

    setIsSubmitting(true);
    try {
      const studentProfile: StudentProfile = {
        id: undefined, // Will be generated by Dexie
        admissionId: application.id!,
        studentNumber: generateStudentNumber(),
        personalInfo: application.personalInfo,
        academicInfo: {
          programId: application.programId,
          intakeId: application.intakeId,
          enrollmentDate: new Date(enrollmentDate),
          currentYear: parseInt(currentYear),
          currentSemester: parseInt(currentSemester),
          gpa: 0,
          creditsEarned: 0,
          totalCredits: program.level === 'bachelor' ? 120 : 
                        program.level === 'master' ? 60 : 
                        program.level === 'diploma' ? 90 : 30,
        },
        feeInfo: {
          totalFees: program.feeStructure.tuition + program.feeStructure.registration + 
                     program.feeStructure.otherFees.reduce((sum, fee) => sum + fee, 0),
          paidAmount: 0,
          outstandingAmount: program.feeStructure.tuition + program.feeStructure.registration + 
                            program.feeStructure.otherFees.reduce((sum, fee) => sum + fee, 0),
          paymentHistory: [],
        },
        status: 'active',
        createdAt: new Date(),
        updatedAt: new Date(),
        synced: false,
      };

      onConvert(studentProfile);
    } catch (error) {
      console.error('Failed to convert application:', error);
    } finally {
      setIsSubmitting(false);
    }
  };

  const handleClose = () => {
    setEnrollmentDate('');
    setCurrentYear('1');
    setCurrentSemester('1');
    onClose();
  };

  if (!application || !intake || !program) return null;

  return (
    <Dialog open={isOpen} onOpenChange={handleClose}>
      <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <GraduationCap className="h-5 w-5" />
            Convert to Student Profile
          </DialogTitle>
          <DialogDescription>
            Convert the accepted application to a student profile and enroll in the program
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-6">
          {/* Application Summary */}
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <User className="h-5 w-5" />
                Applicant Information
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <Label className="text-sm font-medium text-gray-500">Name</Label>
                  <p className="font-medium">
                    {application.personalInfo.firstName} {application.personalInfo.lastName}
                  </p>
                </div>
                <div>
                  <Label className="text-sm font-medium text-gray-500">Email</Label>
                  <p className="font-medium">{application.personalInfo.email}</p>
                </div>
                <div>
                  <Label className="text-sm font-medium text-gray-500">Phone</Label>
                  <p className="font-medium">{application.personalInfo.phone}</p>
                </div>
                <div>
                  <Label className="text-sm font-medium text-gray-500">Status</Label>
                  <Badge className="bg-green-100 text-green-800">
                    {application.status}
                  </Badge>
                </div>
              </div>
            </CardContent>
          </Card>

          {/* Program & Intake Details */}
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <GraduationCap className="h-5 w-5" />
                Program & Intake Details
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <Label className="text-sm font-medium text-gray-500">Program</Label>
                  <p className="font-medium">{program.name}</p>
                  <p className="text-sm text-gray-500">{program.code} • {program.level}</p>
                </div>
                <div>
                  <Label className="text-sm font-medium text-gray-500">Intake</Label>
                  <p className="font-medium">{intake.name}</p>
                  <p className="text-sm text-gray-500">{intake.academicYear}</p>
                </div>
                <div>
                  <Label className="text-sm font-medium text-gray-500">Duration</Label>
                  <p className="font-medium">{program.duration}</p>
                </div>
                <div>
                  <Label className="text-sm font-medium text-gray-500">Intake Status</Label>
                  <Badge variant={intake.status === 'open' ? 'default' : 'secondary'}>
                    {intake.status}
                  </Badge>
                </div>
              </div>
            </CardContent>
          </Card>

          {/* Fee Structure */}
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <DollarSign className="h-5 w-5" />
                Fee Structure
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="space-y-3">
                <div className="flex justify-between">
                  <span>Tuition Fee:</span>
                  <span className="font-medium">${program.feeStructure.tuition.toLocaleString()}</span>
                </div>
                <div className="flex justify-between">
                  <span>Registration Fee:</span>
                  <span className="font-medium">${program.feeStructure.registration.toLocaleString()}</span>
                </div>
                {program.feeStructure.otherFees.map((fee, index) => (
                  <div key={index} className="flex justify-between">
                    <span>Other Fee {index + 1}:</span>
                    <span className="font-medium">${fee.toLocaleString()}</span>
                  </div>
                ))}
                <div className="border-t pt-3 flex justify-between font-bold">
                  <span>Total Fees:</span>
                  <span>${(program.feeStructure.tuition + program.feeStructure.registration + 
                          program.feeStructure.otherFees.reduce((sum, fee) => sum + fee, 0)).toLocaleString()}</span>
                </div>
              </div>
            </CardContent>
          </Card>

          {/* Enrollment Details */}
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Calendar className="h-5 w-5" />
                Enrollment Details
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                <div>
                  <Label htmlFor="enrollmentDate">Enrollment Date *</Label>
                  <Input
                    id="enrollmentDate"
                    type="date"
                    value={enrollmentDate}
                    onChange={(e) => setEnrollmentDate(e.target.value)}
                    required
                  />
                </div>
                
                <div>
                  <Label htmlFor="currentYear">Current Year</Label>
                  <Select value={currentYear} onValueChange={setCurrentYear}>
                    <SelectTrigger>
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      {Array.from({ length: program.level === 'bachelor' ? 4 : 
                                        program.level === 'master' ? 2 : 
                                        program.level === 'diploma' ? 3 : 1 }, (_, i) => i + 1).map(year => (
                        <SelectItem key={year} value={year.toString()}>
                          Year {year}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>
                
                <div>
                  <Label htmlFor="currentSemester">Current Semester</Label>
                  <Select value={currentSemester} onValueChange={setCurrentSemester}>
                    <SelectTrigger>
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="1">Semester 1</SelectItem>
                      <SelectItem value="2">Semester 2</SelectItem>
                      <SelectItem value="3">Semester 3</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
              </div>
            </CardContent>
          </Card>

          {/* Confirmation */}
          <Card className="bg-blue-50 border-blue-200">
            <CardContent className="pt-6">
              <div className="flex items-start gap-3">
                <CheckCircle className="h-5 w-5 text-blue-600 mt-0.5" />
                <div>
                  <h4 className="font-medium text-blue-900 mb-2">What happens next?</h4>
                  <ul className="text-sm text-blue-800 space-y-1">
                    <li>• A unique student number will be generated</li>
                    <li>• Student profile will be created with enrollment details</li>
                    <li>• Fee structure will be set up</li>
                    <li>• Application status will be updated</li>
                    <li>• Student can now access student portal features</li>
                  </ul>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>

        <DialogFooter>
          <Button variant="outline" onClick={handleClose}>
            Cancel
          </Button>
          <Button 
            onClick={handleConvert} 
            disabled={!enrollmentDate || isSubmitting}
            className="bg-green-600 hover:bg-green-700"
          >
            {isSubmitting ? (
              'Converting...'
            ) : (
              <>
                <CheckCircle className="h-4 w-4 mr-2" />
                Convert to Student
              </>
            )}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
};
